[courses.machine-learning]
code = "89-2511"
he = "למידת מכונה"
lecture_group = "02"
lecturer = [
    """ד"ר גליקמן אורן""",
    """פרופ' צ'צ'יק גל""",
    """ד"ר שחם אורי """,
]
tutor_group = "05"
tutor = ["מר בן ארי ניר"]

[courses.artificial-intelligence]
code = "89-5570"
he = "בינה מלאכותית"
lecture_group = "06"
lecturer = [
    """פרופ' קמינקא גל""",
    """ד"ר שלייפמן אלכסנדר""",
]
tutor_group = "10"
tutor = ["מר יצחקי דוד"]
