[courses.machine-learning]
code = "89-2511"
he = "למידת מכונה"
lecture_group = "02"
lecturer = [
    """ד"ר אורן גליקמן""",
    """פרופ' גל צ'צ'יק""",
    """ד"ר אורי שחם """,
]
tutor_group = "05"
tutor = ["ניר בן ארי"]

[courses.artificial-intelligence]
code = "89-5570"
he = "בינה מלאכותית"
lecture_group = "06"
lecturer = [
    """פרופ' גל קמינקא""",
    """ד"ר אלכסנדר שלייפמן""",
]
tutor_group = "10"
tutor = ["דוד יצחקי"]
